useCooldown = true
usageCooldown = 900

useUsageLimit = false
usageLimit = 5

usageReducesMaxHealth = true
maxHealthReductionAmount = 2  # 1 heart
# Set to zero to allow dying from too many totem uses
minimumMaxHealth = 0

# Allows enchanted golden apples to restore max health.
notchAppleRestoresMaxHealth = true
maxHealthRestorationAmount = 2
maximumMaxHealth = 20  # 10 hearts

# Disables buffs
disableAbsorption = true
disableFireResistance = true
disableRegeneration = true

# Debuffs
enableBlindness = true
blindnessDuration = 200  # ten seconds
blindnessLevel = 1

enableSlowness = true
slownessDuration = 600  # 30 seconds
slownessLevel = 1

enableWeakness = true
weaknessDuration = 600
weaknessLevel = 1

enableMiningFatigue = true
miningFatigueDuration = 600
miningFatigueLevel = 1

# Instant healing config
minInstantHealthValue = 0.5
maxInstantHealthValue = 20
instantHealthDivider = 2